/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AuthenticatedProgressRouteImport } from './routes/_authenticated/progress'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDietRouteImport } from './routes/_authenticated/diet'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedReviewWeekIdRouteImport } from './routes/_authenticated/review.$weekId'
import { Route as AuthenticatedDayDayIdRouteImport } from './routes/_authenticated/day.$dayId'
import { Route as AdminAdminReportsRouteImport } from './routes/_admin/admin.reports'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin.dashboard'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksSendWeeklyReviewRouteImport } from './routes/api/public/hooks/send-weekly-review'
import { Route as ApiPublicHooksSendRecoveryPromptRouteImport } from './routes/api/public/hooks/send-recovery-prompt'
import { Route as ApiPublicHooksSendDailyReminderRouteImport } from './routes/api/public/hooks/send-daily-reminder'
import { Route as ApiPublicHooksRecomputeHabitScoresRouteImport } from './routes/api/public/hooks/recompute-habit-scores'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProgressRoute = AuthenticatedProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDietRoute = AuthenticatedDietRouteImport.update({
  id: '/diet',
  path: '/diet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewWeekIdRoute =
  AuthenticatedReviewWeekIdRouteImport.update({
    id: '/review/$weekId',
    path: '/review/$weekId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDayDayIdRoute = AuthenticatedDayDayIdRouteImport.update({
  id: '/day/$dayId',
  path: '/day/$dayId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminAdminReportsRoute = AdminAdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendWeeklyReviewRoute =
  ApiPublicHooksSendWeeklyReviewRouteImport.update({
    id: '/api/public/hooks/send-weekly-review',
    path: '/api/public/hooks/send-weekly-review',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendRecoveryPromptRoute =
  ApiPublicHooksSendRecoveryPromptRouteImport.update({
    id: '/api/public/hooks/send-recovery-prompt',
    path: '/api/public/hooks/send-recovery-prompt',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksSendDailyReminderRoute =
  ApiPublicHooksSendDailyReminderRouteImport.update({
    id: '/api/public/hooks/send-daily-reminder',
    path: '/api/public/hooks/send-daily-reminder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRecomputeHabitScoresRoute =
  ApiPublicHooksRecomputeHabitScoresRouteImport.update({
    id: '/api/public/hooks/recompute-habit-scores',
    path: '/api/public/hooks/recompute-habit-scores',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/diet': typeof AuthenticatedDietRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/day/$dayId': typeof AuthenticatedDayDayIdRoute
  '/review/$weekId': typeof AuthenticatedReviewWeekIdRoute
  '/api/public/hooks/recompute-habit-scores': typeof ApiPublicHooksRecomputeHabitScoresRoute
  '/api/public/hooks/send-daily-reminder': typeof ApiPublicHooksSendDailyReminderRoute
  '/api/public/hooks/send-recovery-prompt': typeof ApiPublicHooksSendRecoveryPromptRoute
  '/api/public/hooks/send-weekly-review': typeof ApiPublicHooksSendWeeklyReviewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/diet': typeof AuthenticatedDietRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/progress': typeof AuthenticatedProgressRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/reports': typeof AdminAdminReportsRoute
  '/day/$dayId': typeof AuthenticatedDayDayIdRoute
  '/review/$weekId': typeof AuthenticatedReviewWeekIdRoute
  '/api/public/hooks/recompute-habit-scores': typeof ApiPublicHooksRecomputeHabitScoresRoute
  '/api/public/hooks/send-daily-reminder': typeof ApiPublicHooksSendDailyReminderRoute
  '/api/public/hooks/send-recovery-prompt': typeof ApiPublicHooksSendRecoveryPromptRoute
  '/api/public/hooks/send-weekly-review': typeof ApiPublicHooksSendWeeklyReviewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/diet': typeof AuthenticatedDietRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/progress': typeof AuthenticatedProgressRoute
  '/admin/login': typeof AdminLoginRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/reports': typeof AdminAdminReportsRoute
  '/_authenticated/day/$dayId': typeof AuthenticatedDayDayIdRoute
  '/_authenticated/review/$weekId': typeof AuthenticatedReviewWeekIdRoute
  '/api/public/hooks/recompute-habit-scores': typeof ApiPublicHooksRecomputeHabitScoresRoute
  '/api/public/hooks/send-daily-reminder': typeof ApiPublicHooksSendDailyReminderRoute
  '/api/public/hooks/send-recovery-prompt': typeof ApiPublicHooksSendRecoveryPromptRoute
  '/api/public/hooks/send-weekly-review': typeof ApiPublicHooksSendWeeklyReviewRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/calendar'
    | '/diet'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/day/$dayId'
    | '/review/$weekId'
    | '/api/public/hooks/recompute-habit-scores'
    | '/api/public/hooks/send-daily-reminder'
    | '/api/public/hooks/send-recovery-prompt'
    | '/api/public/hooks/send-weekly-review'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/calendar'
    | '/diet'
    | '/home'
    | '/onboarding'
    | '/profile'
    | '/progress'
    | '/admin/login'
    | '/admin/dashboard'
    | '/admin/reports'
    | '/day/$dayId'
    | '/review/$weekId'
    | '/api/public/hooks/recompute-habit-scores'
    | '/api/public/hooks/send-daily-reminder'
    | '/api/public/hooks/send-recovery-prompt'
    | '/api/public/hooks/send-weekly-review'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_admin'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/calendar'
    | '/_authenticated/diet'
    | '/_authenticated/home'
    | '/_authenticated/onboarding'
    | '/_authenticated/profile'
    | '/_authenticated/progress'
    | '/admin/login'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/reports'
    | '/_authenticated/day/$dayId'
    | '/_authenticated/review/$weekId'
    | '/api/public/hooks/recompute-habit-scores'
    | '/api/public/hooks/send-daily-reminder'
    | '/api/public/hooks/send-recovery-prompt'
    | '/api/public/hooks/send-weekly-review'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiPublicHooksRecomputeHabitScoresRoute: typeof ApiPublicHooksRecomputeHabitScoresRoute
  ApiPublicHooksSendDailyReminderRoute: typeof ApiPublicHooksSendDailyReminderRoute
  ApiPublicHooksSendRecoveryPromptRoute: typeof ApiPublicHooksSendRecoveryPromptRoute
  ApiPublicHooksSendWeeklyReviewRoute: typeof ApiPublicHooksSendWeeklyReviewRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/progress': {
      id: '/_authenticated/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof AuthenticatedProgressRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/diet': {
      id: '/_authenticated/diet'
      path: '/diet'
      fullPath: '/diet'
      preLoaderRoute: typeof AuthenticatedDietRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review/$weekId': {
      id: '/_authenticated/review/$weekId'
      path: '/review/$weekId'
      fullPath: '/review/$weekId'
      preLoaderRoute: typeof AuthenticatedReviewWeekIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/day/$dayId': {
      id: '/_authenticated/day/$dayId'
      path: '/day/$dayId'
      fullPath: '/day/$dayId'
      preLoaderRoute: typeof AuthenticatedDayDayIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_admin/admin/reports': {
      id: '/_admin/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminAdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-weekly-review': {
      id: '/api/public/hooks/send-weekly-review'
      path: '/api/public/hooks/send-weekly-review'
      fullPath: '/api/public/hooks/send-weekly-review'
      preLoaderRoute: typeof ApiPublicHooksSendWeeklyReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-recovery-prompt': {
      id: '/api/public/hooks/send-recovery-prompt'
      path: '/api/public/hooks/send-recovery-prompt'
      fullPath: '/api/public/hooks/send-recovery-prompt'
      preLoaderRoute: typeof ApiPublicHooksSendRecoveryPromptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/send-daily-reminder': {
      id: '/api/public/hooks/send-daily-reminder'
      path: '/api/public/hooks/send-daily-reminder'
      fullPath: '/api/public/hooks/send-daily-reminder'
      preLoaderRoute: typeof ApiPublicHooksSendDailyReminderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/recompute-habit-scores': {
      id: '/api/public/hooks/recompute-habit-scores'
      path: '/api/public/hooks/recompute-habit-scores'
      fullPath: '/api/public/hooks/recompute-habit-scores'
      preLoaderRoute: typeof ApiPublicHooksRecomputeHabitScoresRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDietRoute: typeof AuthenticatedDietRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedProgressRoute: typeof AuthenticatedProgressRoute
  AuthenticatedDayDayIdRoute: typeof AuthenticatedDayDayIdRoute
  AuthenticatedReviewWeekIdRoute: typeof AuthenticatedReviewWeekIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDietRoute: AuthenticatedDietRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedProgressRoute: AuthenticatedProgressRoute,
  AuthenticatedDayDayIdRoute: AuthenticatedDayDayIdRoute,
  AuthenticatedReviewWeekIdRoute: AuthenticatedReviewWeekIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminReportsRoute: typeof AdminAdminReportsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminReportsRoute: AdminAdminReportsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiPublicHooksRecomputeHabitScoresRoute:
    ApiPublicHooksRecomputeHabitScoresRoute,
  ApiPublicHooksSendDailyReminderRoute: ApiPublicHooksSendDailyReminderRoute,
  ApiPublicHooksSendRecoveryPromptRoute: ApiPublicHooksSendRecoveryPromptRoute,
  ApiPublicHooksSendWeeklyReviewRoute: ApiPublicHooksSendWeeklyReviewRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
